apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "httpcatch.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "httpcatch.labels" . | nindent 4 }}
  {{- include "httpcatch.annotations" (dict "ctx" .) | nindent 2 }}
data:
  config.yaml: |
{{ include "httpcatch.config" . | indent 4 }}
