{{- if not .Values.adminToken.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "httpcatch.adminTokenSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "httpcatch.labels" . | nindent 4 }}
  {{- include "httpcatch.annotations" (dict "ctx" .) | nindent 2 }}
type: Opaque
data:
  admin-token: {{ include "httpcatch.adminToken" . | b64enc | quote }}
{{- end }}
